const pokemonLinearGradients = {
    grass: "bg-gradient-to-t from-black to-green-500",
    fire: "bg-gradient-to-t from-black to-red-500",
    ice: "bg-gradient-to-t from-black to-gray-500",
    dark: "bg-gradient-to-t from-black to-blue-500",
    fairy: "bg-gradient-to-t from-black to-orange-500",
    shadow: "bg-gradient-to-t from-black to-purple-500",
    water: "bg-gradient-to-t from-black to-blue-300",
    bug: "bg-gradient-to-t from-black to-green-200",
    normal:"bg-gradient-to-t from-black to-brown-200",
    fighting:"bg-gradient-to-t from-black to-golden-200",
    ground:"bg-gradient-to-t from-black to-green-200",
    rock:"bg-gradient-to-t from-black to-green-200",
    ghost:"bg-gradient-to-t from-black to-purple-200",
    steel:"bg-gradient-to-t from-black to-green-200",
    electric:"bg-gradient-to-t from-black to-yellow-500",
    psychic:"bg-gradient-to-t from-black to-green-200",
    ice:"bg-gradient-to-t from-black to-green-200",
    dragon:"bg-gradient-to-t from-black to-green-200",
    dark:"bg-gradient-to-t from-black to-green-200",
    fairy:"bg-gradient-to-t from-black to-green-200",
    unknown:"bg-gradient-to-t from-black to-green-200",
    poison:"bg-gradient-to-t from-black to-pink-200",
  }
  
const borderPokemon = {
    grass: "border-green-500",
    fire: "border-red-500",
    ice: "border-gray-500",
    dark: "border-blue-500",
    fairy: "border-orange-500",
    shadow: "border-purple-500",
    water: "border-blue-300",
    bug: "border-green-200",
    normal:"border-brown-500",
    fighting:"border-golden-500",
    ground:"border-green-500",
    rock:"border-green-500",
    ghost:"border-purple-400",
    steel:"border-green-500",
    electric:"border-yellow-500",
    psychic:"border-green-500",
    ice:"border-green-500",
    dragon:"border-green-500",
    dark:"border-green-500",
    fairy:"border-green-500",
    unknown:"border-green-500",
    poison:"border-pink-500",
  
  }

